name: sadamov
description: "Desafio Técnico - Ocorrência de Transporte (Offline → Sync)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Navegação e DI
  flutter_modular: ^6.4.1
  
  # Estado
  mobx: ^2.3.0
  flutter_mobx: ^2.1.0
  
  # Persistência
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Câmera e Imagens
  image_picker: ^1.0.7
  permission_handler: ^12.0.0
  
  # Assinatura
  signature: ^5.4.0
  
  # Background Jobs
  workmanager: ^0.5.2
  
  # Máscaras
  mask_text_input_formatter: ^2.9.0
  
  # Utilitários
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # MobX Code Generation
  build_runner: ^2.4.7
  mobx_codegen: ^2.4.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icon/
    - assets/img/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
